Repository i2ml/Portail_saad, pull requests merged in 2022-06, with the labels that each got.

#27 Ajout des infos de seeding #26 #21
  README.md
  app/Database/Migrations/2022-06-02-125448_CreateSaad.php
  app/Database/Seeds/.gitkeep
  app/Database/Seeds/SaadsSeeder.php
Labels: Database

#41 Small refactor getsaad #6
  app/Models/SaadModel.php
Labels: refactoring

#66 #38
  app/Config/Routes.php
  app/Controllers/PersonController.php
  app/Models/PersonneModel.php
  app/Views/changePassword.php
  app/Views/connexionReussie.php
Labels: Enhancement, Database, Front

#74 Suppression de l'image du saad du serveur
  app/Controllers/SaadController.php
  app/Models/SaadModel.php
Labels: Enhancement
